### ISSUE TITLE
localhost not accessible in gradio  

### ISSUE THREAD

**Issue by errortm** [qnguyen3/chat-with-mlx#13]
User
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mlx-chat/bin/chat-with-mlx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/tangmin/chat-with-mlx/chat_with_mlx/app.py", line 239, in main
    demo.launch(inbrowser=True)
  File "/opt/anaconda3/envs/mlx-chat/lib/python3.11/site-packages/gradio/blocks.py", line 2064, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by qnguyen3** [comment]
are you running anything else that would take away the localhost?

**Comment by guruhao** [comment]
I had same issue due to proxy of env var (http_proxy or https_proxy)
It runs ok by the command below 
export no_proxy="localhost,127.0.0.1"

**Comment by errortm** [comment]
> I had same issue due to proxy of env var (http_proxy or https_proxy) It runs ok by the command below export no_proxy="localhost,127.0.0.1"

I have a Docker container running on port 80. I'm going to shut down Docker to see if that fixes the issue.

**Comment by onuralpszr** [comment]
@errortm If your problem continues please let us know, I am closing this as complete for now.
