### ISSUE TITLE
Issue with ForwardRef._evaluate()

### ISSUE THREAD

**Issue by happy99king** [qnguyen3/chat-with-mlx#173]
Dear Developer,

I encountered an issue when trying to run the `chat-with-mlx` project. When I open the app in the terminal, I get the following error message: 

```
ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

Could you please provide guidance on how to resolve this issue? 

Thank you for your assistance.

Best regards

**Comment by qnguyen3** [comment]
Helllo @happy99king, i suggest using python 3.11 follow [this thread](https://stackoverflow.com/questions/78593700/langchain-community-langchain-packages-giving-error-missing-1-required-keywor)
