### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by zhouhao27** [qnguyen3/chat-with-mlx#178]
Based on the `README.md` file:

> Start the app: chat-with-mlx

But `chat-with-mlx` is a folder. How to run?

**Comment by 100ZZ** [comment]
(mlx)  $ chat-with-mlx
Starting MLX Chat on port 7860
Sharing: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by qnguyen3-dopikai** [comment]
@100ZZ you should be able to run it through `localhost:7860` in your browser
