### ISSUE TITLE
how to change chat_with_mlx run in 0.0.0.0:7888 ?

### ISSUE THREAD

**Issue by flyicewei** [qnguyen3/chat-with-mlx#21]
how to change chat_with_mlx run in 0.0.0.0:7888 ? 
thanks!

**Comment by qnguyen3** [comment]
hi, we are still working on this for you to change the port. the update should be by tomorrow! Please be patient xD

**Comment by flyicewei** [comment]
have new version?

**Comment by M4RT1NJB** [comment]
def main():
#    demo.launch(inbrowser=True,share=True)
#    demo.launch(inbrowser=True)
    demo.launch(inbrowser=True,server_name="0.0.0.0",server_port=7888)

**Comment by qnguyen3** [comment]
> have new version?

im still debugging some last features. meanwhile you can use @M4RT1NJB 's approach

**Comment by M4RT1NJB** [comment]
Alternatively set environment variables when starting the app.
`GRADIO_SERVER_NAME=0.0.0.0 GRADIO_SERVER_PORT=7888 python3.11 app.py`
