### ISSUE TITLE
 raise APIConnectionError(request=request) from err

### ISSUE THREAD

**Issue by bigodyssey** [qnguyen3/chat-with-mlx#28]
^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlx/lib/python3.11/site-packages/openai/_base_client.py", line 952, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by einsteinwjd** [comment]
Did you fix it? I had the same problem. Could you help to figure out how to fix it?

**Comment by bigodyssey** [comment]
> Did you fix it? I had the same problem. Could you help to figure out how to fix it?

I found that is caused by downloading models in default way. When download models with others tools, it works rightly. May this help.
