### ISSUE TITLE
can not launch chat-with-mlx

### ISSUE THREAD

**Issue by taozhiyuai** [qnguyen3/chat-with-mlx#32]
can not launch chat-with-mlx.can anyone help?

I have finished **Manual Pip Installation**

save model files to director **quantized-gemma-2b-it**

<img width="1728" alt="截屏2024-03-04 15 58 20" src="https://github.com/qnguyen3/chat-with-mlx/assets/146583103/10bab915-c6d8-4bea-b882-6f75855d4f80">
<img width="1728" alt="截屏2024-03-04 15 58 27" src="https://github.com/qnguyen3/chat-with-mlx/assets/146583103/c55733fe-67d4-4b35-ae03-fd52b554057c">

<img width="1813" alt="截屏2024-03-04 15 58 42" src="https://github.com/qnguyen3/chat-with-mlx/assets/146583103/d475aa44-44c7-4986-a160-5600f7538f44">

**Comment by qnguyen3** [comment]
Hi, I think your connection to HuggingFace is not stable to download to embedding model

**Comment by taozhiyuai** [comment]
> Hi, I think your connection to HuggingFace is not stable to download to embedding model

I have downloaded on my hard disk. can I use it without accessing HF?

**Comment by qnguyen3** [comment]
@taozhiyuai yes, i understand. however, for the first time, you have to connect to the internet for the embedding model to download (not the LLM). After that you can run everything locally
