### ISSUE TITLE
The server encountered an error while selecting and loading the model.

### ISSUE THREAD

**Issue by jinleiviva** [qnguyen3/chat-with-mlx#37]
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by jinleiviva** [comment]
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

**Comment by qnguyen3** [comment]
please refer to https://github.com/qnguyen3/chat-with-mlx/issues/21
