### ISSUE TITLE
Exception occurred: [Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by mmmmmmmm785** [qnguyen3/chat-with-mlx#41]
after downloading a model ,  model status is "Exception occurred: [Errno 2] No such file or directory: 'python'" .

**Comment by onuralpszr** [comment]
> after downloading a model , model status is "Exception occurred: [Errno 2] No such file or directory: 'python'" .

You install without virtualenv I guess ?

**Comment by onuralpszr** [comment]
@mmmmmmmm785  I merged fix but for workaround you can see virtualenv to make it work or you can use git version
