### ISSUE TITLE
the GUI isn't very intuitive?

### ISSUE THREAD

**Issue by RedemptionC** [qnguyen3/chat-with-mlx#46]
I mean, how to use it? select and load the model -> upload file -> ?

after I did the model thing and clicked load, there's a processing number running, but I have no idea what it means
![image](https://github.com/qnguyen3/chat-with-mlx/assets/17563754/ac51304c-d87f-49b3-998e-329b61f5a340)

**Comment by qnguyen3** [comment]
Thank you for the comment, the UI made with Gradio is not the best one. For now, you can just load in a model and chat with it, if you want to chat with a file, then upload a file and hit "start indexing"
