### ISSUE TITLE
{'index_status': 'Indexing Error', 'error_message': "local variable 'splits' referenced before assignment"}

### ISSUE THREAD

**Issue by YiLin198** [qnguyen3/chat-with-mlx#90]
When I choose the model and complete downloads. I click the index button, but return the error {'index_status': 'Indexing Error', 'error_message': "local variable 'splits' referenced before assignment"}

**Comment by qnguyen3** [comment]
Hi, if you just want to chat with a model without a document, dont hit Indexing
